Models/Notifications.cs
namespace Whisper.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Notifications
    {
        [Key]
        public int NotificationID { get; set; }

        public int UserID { get; set; }

        public int? TriggeredByUserID { get; set; }

        public int? PostID { get; set; }

        public int? CommentID { get; set; }

        public int? ConversationID { get; set; }

        public int? FriendshipID { get; set; }

        public int? LikeID { get; set; }

        public int? MessageID { get; set; }

        [StringLength(255)]
        public string NotificationType { get; set; }

        public bool? ReadStatus { get; set; }

        public DateTime? NotificationDate { get; set; }

        public virtual Comments Comments { get; set; }

        public virtual Conversations Conversations { get; set; }

        public virtual Friendships Friendships { get; set; }

        public virtual Posts Posts { get; set; }

        public virtual Users Users { get; set; }

        public virtual Users Users1 { get; set; }

        public virtual Likes Like { get; set; }

        public virtual Messages Message { get; set; }
    }
}

Controllers/AphorismsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Whisper.Models;

namespace Whisper.Controllers
{
    public class AphorismsController : Controller
    {
        private DBContext db = new DBContext();

        // GET: Aphorisms
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var aphorisms = db.Aphorisms.OrderByDescending(a => a.AphorismId).ToList();
            return View(aphorisms);
        }

        [Authorize]
        public ActionResult GetRandomAphorism()
        {
            int count = db.Aphorisms.Count();
            // Assicurati che ci siano aforismi da restituire.
            if (count == 0)
            {
                return Json(new { frase = "Nessun aforisma disponibile." }, JsonRequestBehavior.AllowGet);
            }

            int index = new Random().Next(count);
            var aphorism = db.Aphorisms.OrderBy(a => a.AphorismId).Skip(index).FirstOrDefault();

            // Assicurati che l'aforisma non sia null.
            if (aphorism == null)
            {
                return Json(new { frase = "Errore durante il recupero dell'aforisma." }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { frase = aphorism.Frase }, JsonRequestBehavior.AllowGet);
        }

        // GET: Aphorisms/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Aphorisms/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Aphorisms aphorism)
        {
            if (ModelState.IsValid)
            {
                db.Aphorisms.Add(aphorism);
                db.SaveChanges();
                TempData["success"] = "Aforisma creato con successo";
                return RedirectToAction("Index");
            }

            return View(aphorism);
        }

        // GET: Aphorisms/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            Aphorisms aphorism = db.Aphorisms.Find(id);
            if (aphorism == null)
            {
                return HttpNotFound();
            }
            return View(aphorism);
        }

        // POST: Aphorisms/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Aphorisms aphorism)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aphorism).State = EntityState.Modified;
                db.SaveChanges();
                TempData["success"] = "Aforisma modifica con successo";
                return RedirectToAction("Index");
            }
            return View(aphorism);
        }

        // GET: Aphorisms/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            Aphorisms aphorism = db.Aphorisms.Find(id);
            if (aphorism == null)
            {
                return HttpNotFound();
            }
            return View(aphorism);
        }

        // POST: Aphorisms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Aphorisms aphorism = db.Aphorisms.Find(id);
            db.Aphorisms.Remove(aphorism);
            db.SaveChanges();
            TempData["success"] = "Aforisma cancellato con successo";
            return RedirectToAction("Index");
        }




        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Whisper.Models;

namespace Whisper.Controllers
{
    public class AuthController : Controller
    {
        DBContext db = new DBContext();
        public ActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Posts");
            }

            return View();
        }

        [HttpPost]
        public ActionResult Login(Users user)
        {
            if (User.Identity.IsAuthenticated)
            {
                var currentUser = db.Users.FirstOrDefault(u => u.UserId.ToString() == User.Identity.Name);
                if (currentUser != null && currentUser.Role == "Admin")
                {
                    return RedirectToAction("Index", "Reports");
                }
                else
                {
                    return RedirectToAction("Index", "Posts");
                }
            }

            var loggedUser = db.Users.FirstOrDefault(u => u.Email == user.Email && u.Password == user.Password);

            if (loggedUser == null || loggedUser.Stato == "Bannato")
            {
                if (loggedUser != null && loggedUser.Stato == "Bannato")
                {
                    TempData["error"] = "Questo account è stato bannato e non può accedere.";
                }
                else
                {
                    TempData["error"] = "Nessun utente corrispondente trovato con questa combinazione di email e password.";
                }

                return RedirectToAction("Login");
            }
            else if (loggedUser.IsDeleted)
            {
                TempData["restore"] = true;
                TempData["userId"] = loggedUser.UserId;
                return RedirectToAction("Login");
            }

            FormsAuthentication.SetAuthCookie(loggedUser.UserId.ToString(), true);

            if (loggedUser.Role == "Admin")
            {
                TempData["success"] = "Login effettuato con successo come Admin.";
                return RedirectToAction("Index", "Reports");
            }
            else
            {
                TempData["success"] = "Login effettuato con successo.";
                return RedirectToAction("Index", "Posts");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RestoreAccount(int userId)
        {
            var user = db.Users.Find(userId);
            if (user == null)
            {
                TempData["error"] = "Utente non trovato.";
                return RedirectToAction("Login");
            }

            user.IsDeleted = false;
            db.Entry(user).State = EntityState.Modified;
            db.SaveChanges();

            TempData["success"] = "Account riattivato con successo.";
            FormsAuthentication.SetAuthCookie(userId.ToString(), true);
            return RedirectToAction("Index", "Posts"); 
        }


        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
    }
}

Controllers/NotificationsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Whisper.Models;

namespace Whisper.Controllers
{
    public class NotificationsController : Controller
    {
        private DBContext db = new DBContext();
        // GET: post / comment / like

        [Authorize(Roles = "User")]
        public ActionResult Index()
        {
            CleanupReadNotifications();
            var userId = int.Parse(User.Identity.Name);
            var userNotifications = db.Notifications
                                      .Include(n => n.Users1)
                                      .Where(n => n.UserID == userId && (n.LikeID.HasValue || n.CommentID.HasValue || n.PostID.HasValue))
                                      .OrderByDescending(n => n.NotificationDate)
                                      .ToList();

            return View(userNotifications);
        }

        [HttpPost]
        public ActionResult MarkAllPostsLikesCommentsAsRead()
        {
            var userId = int.Parse(User.Identity.Name);
            var notificationsToMarkRead = db.Notifications
                                             .Where(n => n.UserID == userId
                                                         && (n.PostID.HasValue || n.LikeID.HasValue || n.CommentID.HasValue)
                                                         && (!n.ReadStatus.HasValue || !n.ReadStatus.Value))
                                             .ToList();

            if (!notificationsToMarkRead.Any())
            {
                return Json(new { success = false, message = "Nessuna notifica da aggiornare." });
            }

            foreach (var notification in notificationsToMarkRead)
            {
                notification.ReadStatus = true;
            }

            db.SaveChanges();

            return Json(new { success = true, message = "Tutte le notifiche di post, like e commenti sono state segnate come lette." });
        }



        // GET : Amicizie
        [Authorize(Roles = "User")]
        public ActionResult Friendships()
        {
            CleanupReadNotifications();
            var userId = int.Parse(User.Identity.Name);
            var userNotifications = db.Notifications
                                      .Include(n => n.Users1)
                                      .Where(n => n.UserID == userId && n.FriendshipID.HasValue)
                                      .OrderByDescending(n => n.NotificationDate)
                                      .ToList();

            return View(userNotifications);
        }

        public ActionResult MarkAllFriendshipAsRead()
        {
            var userId = int.Parse(User.Identity.Name);
            var friendshipNotifications = db.Notifications
                         .Where(n => n.UserID == userId
                                     && n.FriendshipID.HasValue // Solo le notifiche di amicizia
                                     && (!n.ReadStatus.HasValue || !n.ReadStatus.Value)) // Non lette
                         .ToList();

            if (!friendshipNotifications.Any())
            {
                return Json(new { success = false, message = "Nessuna notifica di amicizia da aggiornare." });
            }

            foreach (var notification in friendshipNotifications)
            {
                notification.ReadStatus = true;
            }

            db.SaveChanges();

            return Json(new { success = true, message = "Tutte le notifiche di amicizia sono state segnate come lette." });
        }


        // GET : Messaggi
        [Authorize(Roles = "User")]
        public ActionResult Conversations()
        {
            CleanupReadNotifications();
            int userId = int.Parse(User.Identity.Name);
            ViewBag.CurrentUserId = userId;

            // Ottieni il conteggio dei messaggi non letti per l'utente corrente
            ViewBag.UnreadMessagesCount = db.Messages
                                            .Count(m => m.Conversations.User1Id == userId && m.ReadStatus == false && !m.Conversations.User1Deleted ||
                                                        m.Conversations.User2Id == userId && m.ReadStatus == false && !m.Conversations.User2Deleted);

            // Ottieni solo le conversazioni che non sono state cancellate dall'utente corrente
            var userConversations = db.Conversations
                                       .Include(c => c.Notifications)
                                       .Where(c => (c.User1Id == userId && !c.User1Deleted) ||
                                                   (c.User2Id == userId && !c.User2Deleted))
                                       .ToList();

            var users = db.Users.ToDictionary(u => u.UserId, u => u);
            ViewBag.Users = users;

            // Crea un dizionario per tenere traccia dei conteggi dei messaggi non letti per ciascuna conversazione
            var unreadMessageCounts = userConversations.ToDictionary(
                c => c.ConversationId,
                c => GetUnreadMessagesCountForConversation(userId, c.ConversationId));

            // Passa questo dizionario alla vista
            ViewBag.UnreadMessageCounts = unreadMessageCounts;

            return View(userConversations);
        }

        // count dei messaggi non letti 

        private int GetUnreadMessagesCountForConversation(int userId, int conversationId)
        {
            return db.Messages.Count(m => m.ConversationId == conversationId &&
                                          m.UserId != userId &&
                                          !m.ReadStatus);
        }

        // Metodo per aggiornare lo stato di una notifica a "letta"
        [HttpPost]
        public ActionResult MarkNotificationAsRead(int notificationId)
        {
            var notification = db.Notifications.Find(notificationId);
            if (notification != null && notification.UserID.ToString() == User.Identity.Name)
            {
                notification.ReadStatus = true;
                db.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false, message = "Notifica non trovata o utente non autorizzato." });
        }

        [HttpPost]
        public ActionResult MarkMessageAsRead(int notificationId)
        {
            var notification = db.Notifications.Find(notificationId);
            if (notification != null && notification.UserID.ToString() == User.Identity.Name)
            {
                // Trova tutti i messaggi non letti di questa conversazione per l'utente attuale
                var messagesToUpdate = db.Messages
                                         .Where(m => m.ConversationId == notification.ConversationID &&
                                                     m.UserId != notification.UserID &&
                                                     !m.ReadStatus).ToList();

                // Segna tutti i messaggi trovati come letti
                foreach (var message in messagesToUpdate)
                {
                    message.ReadStatus = true;
                }

                // Aggiorna lo stato della notifica
                notification.ReadStatus = true;
                db.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false, message = "Notifica non trovata o utente non autorizzato." });
        }


        // Pulizia delle notifiche lette più vecchie di 24 ore
        private void CleanupReadNotifications()
        {
            var rangeDiControllo = DateTime.UtcNow.AddDays(-1);
            var oldNotifications = db.Notifications
                                     .Where(n => n.ReadStatus == true && n.NotificationDate <= rangeDiControllo)
                                     .ToList();

            db.Notifications.RemoveRange(oldNotifications);
            db.SaveChanges();
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - Whisper</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="//cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

</head>
<body>
    <div class="@GetBodyClass() body-class">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-lilla">
            <div class="container">
                <img src="~/Content/Img/WhisperLogo2.jpg" alt="Logo Whisper" class="logo" />
                @Html.ActionLink("Whisper", "Index", "Home", new { area = "" }, new { @class = "navbar-brand text-shadow shining" })
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Attiva/Disattiva spostamento" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @if (User.IsInRole("User"))
                {
                    <span class="text-white text-shadow visual">@Html.Partial("_aphorism")</span>
                }
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-end">


                    <ul class="navbar-nav ml-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Admin"))
                            {
                                
                                <li class="nav-item text-shadow ml-auto ">
                                    <a href="@Url.Action("Index", "Aphorisms", new { area = "" })" class="btn ms-2 shining">
                                        <i class="bi bi-brilliance"></i> <span class="icon-none">Aforismi</span>
                                    </a>
                                </li>
                                <li class="nav-item text-shadow">
                                    <a href="@Url.Action("Index", "Avatars", new { area = "" })" class="btn ms-2 shining">
                                        <i class="bi bi-emoji-smile-upside-down"></i> <span class="icon-none">Avatar</span>
                                    </a>
                                </li>
                                <li class="nav-item text-shadow">
                                    <a href="@Url.Action("Index", "Sponsors", new { area = "" })" class="btn ms-2 shining">
                                        <i class="bi bi-camera-reels"></i> <span class="icon-none">Sponsor</span>
                                    </a>
                                </li>
                                <li class="nav-item text-shadow">
                                    <a href="@Url.Action("Index", "Posts", new { area = "" })" class="btn ms-2 shining">
                                        <i class="bi bi-house-heart"></i> <span class="icon-none">Home</span>
                                    </a>
                                </li>
                                <li class="nav-item text-shadow">
                                    <a href="@Url.Action("Index", "Reports", new { area = "" })" class="btn ms-2 shining">
                                        <i class="bi bi-ban"></i> <span class="icon-none">Reports</span>
                                    </a>
                                </li>

                            }
                            if (User.IsInRole("User"))
                            {
                                <li class="nav-item text-shadow">
                                    <a href="@Url.Action("Friendships", "Notifications")" class="btn ms-2 shining">
                                        <i class="bi bi-people"></i>
                                        @if (ViewBag.FriendshipNotificationsCount > 0)
                                        {
                                            <span class="notification-count">@ViewBag.FriendshipNotificationsCount</span>
                                        }
                                    </a>
                                </li>
                                <li class="nav-item text-shadow">
                                    <a href="@Url.Action("Conversations", "Notifications")" class="btn ms-2 shining">
                                        <i class="bi bi-chat-dots"></i>
                                        @if (ViewBag.MessageNotificationsCount > 0)
                                        {
                                            <span class="notification-count">@ViewBag.MessageNotificationsCount</span>
                                        }
                                    </a>
                                </li>
                                <li class="nav-item text-shadow">
                                    <a href="@Url.Action("Index", "Notifications")" class="btn ms-2 shining">
                                        <i class="bi bi-bell"></i>
                                        @if (ViewBag.GeneralNotificationsCount > 0)
                                        {
                                            <span class="notification-count">@ViewBag.GeneralNotificationsCount</span>
                                        }
                                    </a>
                                </li>


                                <li class="nav-item text-shadow light">
                                    <a href="@Url.Action("Index", "Posts", new { area = "" })" class="btn ms-2 shining">
                                        <i class="bi bi-house-heart"></i> <span class="icon-none">Home</span>
                                    </a>
                                </li>
                            }

                            <li class="nav-item text-shadow">
                                <a href="@Url.Action("Logout", "Auth", new { area = "" })" class="btn ms-2 shining">
                                    <i class="bi bi-box-arrow-right"></i> <span class="icon-none">Logout</span>
                                </a>
                            </li>

                            <li class="nav-item text-shadow">
                                @if (ViewBag.ShowDefaultIcon == true)
                                {
                                    <a href="@Url.Action("Details", "Users", new { id = User.Identity.Name })" class="btn ms-2 shining">
                                        <i class="bi bi-person-circle"></i> <span class="icon-none">@ViewBag.Username</span> 
                                    </a>
                                }
                                else
                                {
                            <a href="@Url.Action("Details", "Users", new { id = User.Identity.Name })" class="btn shining">
                                <img src="@Url.Content(ViewBag.ProfileImage)" class="avatar-img" alt="Profile Image" style="width:25px; height:25px"> <span class="icon-none">@ViewBag.Username</span>
                            </a>
                                }
                            </li>

                        }
                        else
                        {
                            <li class="nav-item">
                                <a href="@Url.Action("Create", "Users", new { area = "" })" class="btn btn-sm  btn-register ms-2 icon-pro">
                                    <i class="bi bi-heart-pulse"></i> Registrazione
                                </a>
                            </li>

                            <li class="nav-item">
                                <a href="@Url.Action("Login", "Auth", new { area = "" })" class="btn btn-sm  btn-register ms-2 icon-pro">
                                    <i class="bi bi-door-open"></i> Login
                                </a>
                            </li>

                        }
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container body-content">



            <div class="d-flex justify-content-end align-items-start position-relative">
                <div class="w-25 position-absolute top-5 end-0 translate-middle-y" style="opacity: 0.8;">
                    @Html.Partial("_Notification")
                </div>
            </div>

            @RenderBody()
            
        </div>
        <footer class="text-white">
            <hr class="text-white footer" />
            <p class="pb-2 ps-5">&copy; @DateTime.Now.Year - Whisper MarSil™</p>
        </footer>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"></script>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </div>
</body>
</html>

@functions {
    public string GetBodyClass()
    {
        var controller = ViewContext.RouteData.Values["controller"].ToString();
        var action = ViewContext.RouteData.Values["action"].ToString();
        if (controller == "Auth" && action == "Login")
        {
            return "login-background";
        }
        else if (controller == "Users" && action == "Create")
        {
            return "create-background";
        }
        else if(controller == "Users" && action == "Delete" || controller == "Users" && action == "Edit" || controller == "Users" && action == "Details")
        {
            return "profile-background";
        }
        else if (controller == "Posts" && action == "Index" || controller == "Posts" && action == "Create" || controller == "Posts" && action == "Delete" || controller == "Posts" && action == "Edit" || controller == "Posts" && action == "Details")
        {
            return "posts-background";
        }
        else if (controller == "Comments" && action == "Index" || controller == "Comments" && action == "Create" || controller == "Comments" && action == "Delete" || controller == "Comments" && action == "Edit" || controller == "Comments" && action == "Details")
        {
            return "comments-background";
        }
        else if (controller == "Reports" && action == "Index" || controller == "Reports" && action == "Create" || controller == "Reports" && action == "Delete" || controller == "Reports" && action == "Edit" || controller == "Reports" && action == "Details")
        {
            return "reports-background";
        }
        else if (controller == "Sponsors" && action == "Index" || controller == "Sponsors" && action == "Create" || controller == "Sponsors" && action == "Delete" || controller == "Sponsors" && action == "Edit" || controller == "Sponsors" && action == "Details")
        {
            return "sponsor-background";
        }
        else if (controller == "Notifications" && action == "Index" || controller == "Notifications" && action == "Friendships" || controller == "Notifications" && action == "Conversations" || controller == "Conversations" && action == "Index" || controller == "Conversations" && action == "Delete")
        {
            return "notifications-background";
        }
        else if (controller == "Conversations" && action == "Index" || controller == "Conversations" && action == "Delete" || controller == "Conversations" && action == "Details")
        {
            return "notifications-background";
        }
        else if (controller == "Avatars" && action == "Index" || controller == "Avatars" && action == "Create" || controller == "Avatars" && action == "Delete")
        {
            return "avatars-background";
        }
        else if (controller == "Aphorisms" && action == "Index" || controller == "Aphorisms" && action == "Create" || controller == "Aphorisms" && action == "Delete" || controller == "Aphorisms" && action == "Edit")
        {
            return "aphorisms-background";
        }
        else
        {
            return string.Empty;
        }
    }
}

Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Successo!</strong>✔ @TempData["success"].ToString()
    </div>
}


@if (TempData["error"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Errore!</strong>❌ @TempData["error"].ToString()
    </div>
}

@if (TempData["userUnable"] != null)
{
    <div class="alert alert-dark alert-dismissible fade show" role="alert">
        <strong class="text-danger">Utente Inattivo!</strong>👽 @TempData["userUnable"].ToString()
    </div>
}

<script>
    window.setTimeout(function () {
        $(".alert-dismissible").fadeTo(500, 0).slideUp(500, function () {
            $(this).remove();
        });
    }, 3500);
</script>

Views/Shared/_RandomSponsor.cshtml
@model List<Whisper.Models.Sponsors>

@{
    int sponsorIndex = 0;
}

@foreach (var sponsor in Model)
{
    <div class="card shadow mt-3 text-shadow sponsor-container w-100" id="sponsor-container-@sponsorIndex" style="width: 18rem;">

        @if (!string.IsNullOrEmpty(sponsor.Foto))
        {
            <img class="card-img-top img-fluid" src="@Url.Content(sponsor.Foto)" alt="Immagine dello sponsor">
        }
        <div class="card-body">
            <h5 class="card-title">@sponsor.Titolo</h5>
            <p class="card-text">@sponsor.Description</p>
        </div>
    </div>
    sponsorIndex++;
}


@if (Model != null && Model.Count == 3)
{
    <script>
        if (typeof window.updateRandomSponsor === 'undefined') {
            window.updateRandomSponsor = function() {
                fetch('@Url.Action("RandomSponsor", "Sponsors")')
                    .then(response => response.text())
                    .then(html => {
                        var sponsorHTML = html.split('<div class="card shadow mt-3 text-shadow sponsor-container w-100"');
                        var containers = document.querySelectorAll('.sponsor-container');
                        containers.forEach((container, index) => {
                            var newContent = '<div class="card shadow mt-3 text-shadow sponsor-container w-100"' + sponsorHTML[index + 1];
                            container.outerHTML = newContent;
                        });
                    })
                    .catch(error => {
                        console.error('Errore nel caricamento della pubblicità:', error);
                    });
            };

            setInterval(window.updateRandomSponsor, 30000);
        }
    </script>
}