Controllers/SponsorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Whisper.Models;

namespace Whisper.Controllers
{
    public class SponsorsController : Controller
    {
        private DBContext db = new DBContext();

        // GET: Sponsors
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var sponsors = db.Sponsors
                .Include(s => s.Users)
                .OrderByDescending(s => s.SponsorId);

            return View(sponsors.ToList());
        }

        // GET: Sponsors/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sponsors sponsors = db.Sponsors.Find(id);
            if (sponsors == null)
            {
                return HttpNotFound();
            }
            return View(sponsors);
        }

        // GET: Sponsors/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind(Include = "SponsorId,Titolo,Description")] Sponsors sponsors, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                int userId;
                if (int.TryParse(User.Identity.Name, out userId))
                {
                    var currentUser = db.Users.FirstOrDefault(u => u.UserId == userId);
                    if (currentUser != null)
                    {
                        if (upload != null && upload.ContentLength > 0)
                        {
                           
                            var fileName = Guid.NewGuid().ToString() + Path.GetExtension(upload.FileName);
                            var path = Path.Combine(Server.MapPath("~/Uploads"), fileName);

                       
                            try
                            {
                                upload.SaveAs(path);
                                sponsors.Foto = "~/Uploads/" + fileName;
                            }
                            catch (Exception ex)
                            {
                              
                                ModelState.AddModelError("", "Errore durante il salvataggio del file: " + ex.Message);
                                return View(sponsors);
                            }
                        }

                        sponsors.UserId = userId;
                        db.Sponsors.Add(sponsors);
                        db.SaveChanges();
                        TempData["success"] = "Sponsor aggiunto correttamente";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Utente non trovato.");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Errore nel parsing dell'UserID.");
                }
            }

            return View(sponsors);
        }


        // Pubblicità random
        public ActionResult RandomSponsor()
        {
            var sponsorsList = db.Sponsors.ToList();
            var chosenSponsors = new List<Sponsors>();

            while (chosenSponsors.Count < 3)
            {
                var randomIndex = new Random().Next(sponsorsList.Count);
                var randomSponsor = sponsorsList[randomIndex];
                if (!chosenSponsors.Contains(randomSponsor))
                {
                    chosenSponsors.Add(randomSponsor);
                }
            }

            return PartialView("_RandomSponsor", chosenSponsors);
        }


        // GET: Sponsors/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sponsors sponsors = db.Sponsors.Find(id);
            if (sponsors == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.Users, "UserId", "Username", sponsors.UserId);
            return View(sponsors);
        }

        // POST: Sponsors/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind(Include = "SponsorId,Titolo,Description")] Sponsors sponsors, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                var existingSponsor = db.Sponsors.Find(id);
                if (existingSponsor == null)
                {
                    return HttpNotFound();
                }

                existingSponsor.Titolo = sponsors.Titolo;
                existingSponsor.Description = sponsors.Description;

                if (upload != null && upload.ContentLength > 0)
                {
                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(upload.FileName);
                    var path = Path.Combine(Server.MapPath("~/Uploads"), fileName);

                    try
                    {
                        upload.SaveAs(path);
                        existingSponsor.Foto = "~/Uploads/" + fileName;
                    }
                    catch (Exception ex)
                    {
                        ModelState.AddModelError("", "Errore durante il salvataggio del file: " + ex.Message);
                        return View(sponsors);
                    }
                }

                db.Entry(existingSponsor).State = EntityState.Modified;
                db.SaveChanges();
                TempData["success"] = "Sponsor aggiornato correttamente";
                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.Users, "UserId", "Username", sponsors.UserId);
            return View(sponsors);
        }


        // GET: Sponsors/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sponsors sponsors = db.Sponsors.Find(id);
            if (sponsors == null)
            {
                return HttpNotFound();
            }
            return View(sponsors);
        }

        // POST: Sponsors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sponsors sponsors = db.Sponsors.Find(id);
            db.Sponsors.Remove(sponsors);
            db.SaveChanges();
            TempData["success"] = "Sponsor eliminato correttamente";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Sponsors/Create.cshtml
@model Whisper.Models.Sponsors

@{
    ViewBag.Title = "Create";
}

<div class="login-container">
    <div class="login-box">
        <h2>Aggiungi pubblicità <i class="bi bi-cassette"></i></h2>
        @using (Html.BeginForm("Create", "Sponsors", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <label class="color-wine fw-bold">Titolo Sponsor</label>
                @Html.EditorFor(model => model.Titolo, new { htmlAttributes = new { @class = "form-control", id = "Titolo" } })
                @Html.ValidationMessageFor(model => model.Titolo, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label class="color-wine fw-bold">Descrizione Sponsor</label>
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", rows = "5", placeholder = "Inserisci una descrizione per lo sponsor...", id = "Description", maxlength = "120", style = "resize: none;" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                <span id="description-validation-message" class="text-danger" style="display:none;">Il campo Descrizione è obbligatorio.</span>
                <span id="char-count" class="text-secondary">0/120</span>
            </div>


            <div class="form-group custom-file-upload">
                <!-- anteprima dell'immagine -->
                <img id="imagePreview" src="#" alt="Anteprima immagine" style="max-width: 100%; height: auto; display: none;" />

                <label for="Foto" class="file-upload-container btn btn-sm btn-warning my-2" style="background-color: #ffc107; color: black;">
                    <i class="bi bi-upload"></i> Carica una foto
                    <input type="file" name="upload" id="Foto" class="form-control-file" hidden />
                </label>
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>


            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-sm btn-login" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-sm btn-back" })
            </div>
        }

    </div>
</div>

<script type="text/javascript">
    document.getElementById('Foto').onchange = function (event) {
        var reader = new FileReader();
        reader.onload = function () {
            var output = document.getElementById('imagePreview');
            output.src = reader.result;
            output.style.display = 'block';
        };
        reader.readAsDataURL(event.target.files[0]);
    };
</script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var description = document.getElementById('Description');
        var validationMessageElement = document.getElementById('description-validation-message');
        var charCountElement = document.getElementById('char-count');

        // Funzione per aggiornare il conteggio dei caratteri
        function updateCharCount() {
            var textLength = description.value.length;
            charCountElement.textContent = `${textLength}/120`;
        }

        // Aggiorna il conteggio dei caratteri all'avvio
        updateCharCount();

        // Aggiorna il conteggio dei caratteri ogni volta che l'utente digita
        description.addEventListener('input', updateCharCount);

        // Aggiungi la logica di validazione al submit del form
        var form = document.querySelector('form');
        form.addEventListener('submit', function (event) {
            if (!description.value.trim()) {
                validationMessageElement.style.display = 'block';
                event.preventDefault();
            } else {
                validationMessageElement.style.display = 'none';
            }
        });
    });
</script>

Views/Sponsors/Delete.cshtml
@model Whisper.Models.Sponsors

@{
    ViewBag.Title = "Sponsor Delete";
}

<div class="login-container">
    <div class="login-box cont-3d">

        <p class="alert alert-danger">Sei sicuro di voler eliminare il tuo Bisbiglio? Questa azione è irreversibile.</p>
        <div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    <label class="fw-bold color-wine">Admin</label>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Users.Username)
                </dd>

                <dt>
                    <label class="fw-bold color-wine">Titolo Sponsor</label>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Titolo)
                </dd>

                <dt>
                    <label class="fw-bold color-wine">Contenuto Sponsor</label>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>

                <dt>
                    <label class="fw-bold color-wine">Foto</label>
                </dt>
                <dd>
                    <img src="@Url.Content(Model.Foto)" alt="Immagine" style="max-width: 100%;" />
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Elimina Sponsor" class="btn btn-sm btn-danger text-white" />
            @Html.ActionLink("Annulla", "Index", null, new { @class = "btn btn-sm btn-back ms-2 text-white" })

        </div>
            }
        </div>
        </div>
</div>

Views/Sponsors/Details.cshtml
@model Whisper.Models.Sponsors

@{
    ViewBag.Title = "Sponsor Details";
}

<div class="login-container text-shadow">
    <div class="login-box cont-3d">
        <div>

            <dt>
                <label class="fw-bold color-wine">Foto</label>
            </dt>
            <dd>
                <img src="@Url.Content(Model.Foto)" alt="Immagine" style="max-width: 100%;" />
            </dd>

            <dl class="dl-horizontal">
                <dt>
                    <label class="fw-bold color-wine">Admin</label>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Users.Username)
                </dd>

                <dt>
                    <label class="fw-bold color-wine">Titolo Sponsor</label>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Titolo)
                </dd>

                <dt>
                    <label class="fw-bold color-wine">Contenuto Sponsor</label>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>



            </dl>
        </div>
        <div class="form-actions no-color">
            @Html.ActionLink("Edit", "Edit", new { id = Model.SponsorId }, new { @class = "btn btn-sm btn-login" })
            @Html.ActionLink("Annulla", "Index", null, new { @class = "btn btn-sm btn-back ms-2 " })
        </div>

        </div>
</div>

Views/Sponsors/Edit.cshtml
@model Whisper.Models.Sponsors

@{
    ViewBag.Title = "Edit";
}

<div class="login-container text-shadow">
    <div class="login-box cont-3d">
        <h2>Modifica pubblicità <i class="bi bi-pencil-square"></i></h2>
        @using (Html.BeginForm("Edit", "Sponsors", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()

            @Html.HiddenFor(model => model.SponsorId)

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <label class="color-wine fw-bold">Titolo Sponsor</label>
                @Html.EditorFor(model => model.Titolo, new { htmlAttributes = new { @class = "form-control", id = "Titolo" } })
                @Html.ValidationMessageFor(model => model.Titolo, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label class="color-wine fw-bold">Descrizione Sponsor</label>
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", rows = "5", placeholder = "Inserisci una descrizione per lo sponsor...", id = "Description", maxlength = "120", style = "resize: none;" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                <span id="description-validation-message" class="text-danger" style="display:none;">Il campo Descrizione è obbligatorio.</span>
                <span id="char-count" class="text-secondary">0/120</span>
            </div>

            <!-- Anteprima immagine esistente -->
            <div class="form-group existing-image-preview">
                <label class="color-wine fw-bold">Anteprima Immagine Attuale</label>
                <img src="@Url.Content(Model.Foto)" alt="Anteprima immagine attuale" class="existing-image-preview" style="max-width: 100%; height: auto;" />
            </div>
            <div class="form-group image-preview-container" style="text-align: center;">
                <!-- L'anteprima dell'immagine verrà inserita qui -->
            </div>


            <div class="form-group custom-file-upload">
                <!-- Caricamento nuova immagine -->
                <label for="Foto" class="file-upload-container btn btn-sm btn-warning my-2" style="background-color: #ffc107; color: black;">
                    <i class="bi bi-upload"></i> Carica una nuova foto
                    <input type="file" name="upload" id="Foto" class="form-control-file" hidden />
                </label>
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-sm btn-login" />
                @Html.ActionLink("Annulla", "Index", null, new { @class = "btn btn-sm btn-back" })
            </div>
        }
    </div>
</div>

<script type="text/javascript">
    document.getElementById('Foto').onchange = function (event) {
        var reader = new FileReader();
        reader.onload = function () {
            // Nasconde o rimuove l'anteprima dell'immagine esistente
            var existingImagePreview = document.querySelector('.existing-image-preview');
            if (existingImagePreview) {
                existingImagePreview.style.display = 'none';
            }

            // Crea o aggiorna l'anteprima della nuova immagine caricata
            var newImagePreview = document.getElementById('imagePreview');
            if (!newImagePreview) {
                newImagePreview = document.createElement('img');
                newImagePreview.id = 'imagePreview';
                newImagePreview.style = 'max-width: 100%; height: auto; display: block; margin: 0 auto;';
            }
            newImagePreview.src = reader.result;

            // Aggiunge l'anteprima dell'immagine nel contenitore specificato
            document.querySelector('.image-preview-container').appendChild(newImagePreview);
        };
        reader.readAsDataURL(event.target.files[0]);
    };


</script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var description = document.getElementById('Description');
        var validationMessageElement = document.getElementById('description-validation-message');
        var charCountElement = document.getElementById('char-count');

        function updateCharCount() {
            var textLength = description.value.length;
            charCountElement.textContent = `${textLength}/120`;
        }

        updateCharCount();
        description.addEventListener('input', updateCharCount);

        var form = document.querySelector('form');
        form.addEventListener('submit', function (event) {
            if (!description.value.trim()) {
                validationMessageElement.style.display = 'block';
                event.preventDefault();
            } else {
                validationMessageElement.style.display = 'none';
            }
        });
    });
</script>

Views/Sponsors/Index.cshtml
@model IEnumerable<Whisper.Models.Sponsors>

@{
    ViewBag.Title = "Index";
}
<p>
    @Html.ActionLink("✒ Inserisci nuova pubblicità", "Create", null, new { @class = "btn btn-sm btn-warning fw-bold text-dark mt-5 mb-3 text-shadow" })
</p>

<div class="row text-shadow row-custom">
    @foreach (var item in Model)
    {
        <div class=" col-lg-4 d-flex align-items-stretch">
            <div class="card mb-4 shadow-sm w-100 d-flex flex-column">
                <div style="height: 200px; overflow: hidden;">
                    <img class="card-img-top img-fluid" src="@Url.Content(item.Foto)" alt="Immagine dello sponsor" style="object-fit: cover; height: 100%; width: 100%;">
                </div>
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">@item.Titolo</h5>
                    <p class="card-text flex-fill">@item.Description</p>
                </div>
                <div class="card-footer mt-auto d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        @Html.ActionLink("Edit", "Edit", new { id = item.SponsorId }, new { @class = "btn btn-sm btn-login text-shadow text-button" })
                        @Html.ActionLink("Details", "Details", new { id = item.SponsorId }, new { @class = "btn btn-sm btn-back text-shadow text-button" })
                        @Html.ActionLink("Delete", "Delete", new { id = item.SponsorId }, new { @class = "btn btn-sm btn-danger text-shadow" })
                    </div>
                    <small class="text-muted">Admin: @item.Users.Username</small>
                </div>
            </div>
        </div>
    }
</div>