Models/Avatars.cs
namespace Whisper.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Avatars
    {
        [Key]
        public int AvatarId { get; set; } 
        public string Foto { get; set; } 
    }
}

Controllers/AvatarsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Whisper.Models;

namespace Whisper.Controllers
{
    public class AvatarsController : Controller
    {
        private DBContext db = new DBContext();

        // GET: Avatars
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(db.Avatars.ToList());
        }

        // GET: Avatars/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Avatars/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AvatarId")] Avatars avatars, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(upload.FileName);
                    var path = Path.Combine(Server.MapPath("~/Uploads"), fileName);
                    upload.SaveAs(path);
                    avatars.Foto = "~/Uploads/" + fileName;
                }

                db.Avatars.Add(avatars);
                db.SaveChanges();
                TempData["success"] = "Avatar caricato con successo";
                return RedirectToAction("Index");
            }

            return View(avatars);
        }

        // GET: Avatars/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Avatars avatars = db.Avatars.Find(id);
            if (avatars == null)
            {
                return HttpNotFound();
            }
            return View(avatars);
        }

        // POST: Avatars/Delete/5
        // POST: Avatars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Avatars avatar = db.Avatars.Find(id);
            if (avatar == null)
            {
                return HttpNotFound();
            }

            // Controlla se l'avatar è utilizzato da qualche utente
            var usersWithAvatar = db.Users.Where(u => u.AvatarId == id).ToList();
            if (usersWithAvatar.Any())
            {
                // Se l'avatar è utilizzato da almeno un utente
                foreach (var user in usersWithAvatar)
                {
                    user.AvatarId = 20; 
                }
            }

            db.Avatars.Remove(avatar);
            db.SaveChanges();
            TempData["success"] = "Avatar eliminato con successo";
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Avatars/Create.cshtml
@model Whisper.Models.Avatars

@{
    ViewBag.Title = "Create";
}

<div class="login-container">
    <div class="login-box text-shadow cont-3d">
        <h2>Aggiungi Avatar</h2>
        @using (Html.BeginForm("Create", "Avatars", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group custom-file-upload">
                <!-- anteprima dell'immagine -->
                <img class="avatar-img" id="imagePreview" src="#" alt="Anteprima immagine" style="max-width: 100%; height: auto; display: none;" />

                <label for="upload" class="file-upload-container btn btn-sm btn-warning my-2" style="background-color: #ffc107; color: black;">
                    <i class="bi bi-upload"></i> Carica un'immagine
                    <input type="file" name="upload" id="upload" class="form-control-file" hidden />
                </label>
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-sm btn-login text-shadow" />
                @Html.ActionLink("Annulla", "Index", null, new { @class = "btn btn-sm btn-back text-shadow" })
            </div>
        }
    </div>
</div>

<script type="text/javascript">
    document.getElementById('upload').onchange = function (event) {
        var reader = new FileReader();
        reader.onload = function () {
            var output = document.getElementById('imagePreview');
            output.src = reader.result;
            output.style.display = 'block';
        };
        reader.readAsDataURL(event.target.files[0]);
    };
</script>

Views/Avatars/Delete.cshtml
@model Whisper.Models.Avatars

@{
    ViewBag.Title = "Delete";
}

<div class="login-container">
    <div class="login-box text-shadow cont-3d">
        <p class="alert alert-danger ">Sei sicuro di voler eliminare questo avatar? Questa azione è irreversibile.</p>
        <div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Foto)
                </dt>

                <dd>
                    <img class="avatar-img" src="@Url.Content(Model.Foto)" alt="Avatar Image" style="max-width: 200px; height: auto;" />
                </dd>
            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Elimina Avatar" class="btn btn-sm btn-danger text-white text-shadow" />
                    @Html.ActionLink("Annulla", "Index", null, new { @class = "btn btn-sm btn-back ms-2 text-shadow" })
                </div>
            }
        </div>
    </div>
</div>

Views/Avatars/Index.cshtml
@model IEnumerable<Whisper.Models.Avatars>

@{
    ViewBag.Title = "Index";
}

@Html.ActionLink("👽 Aggiungi Avatar", "Create", "Avatars", new { @class = "btn btn-sm text-dark text-shadow fw-bold btn-warning ms-3 my-5" })

<div class="container text-shadow m-auto" style="max-height:90vh; overflow-y: auto;">
    <div class="row justify-content-center">
        @foreach (var avatar in Model)
        {
            if (avatar.AvatarId != 20)
            {
                <div class="col-12 col-sm-12 col-md-4 col-lg-3 mb-3 d-flex">
                    <div class="card cont-3d m-auto" style="width: 18rem;">
                        <img src="@Url.Content(avatar.Foto)" class="card-img-top avatar-img m-auto mt-4" alt="Avatar">
                        <div class="card-body">
                            <h5 class="card-text">Avatar numero @avatar.AvatarId.</h5>
                            @Html.ActionLink("Delete", "Delete", new { id = avatar.AvatarId }, new { @class = "btn btn-danger text-shadow" })
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>